headers:
  authority: 'www.aliexpress.com'
  method: 'GET'
  scheme: 'https'
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
  accept-encoding: 'gzip, deflate, br'
  accept-language: 'zh-CN,zh;q=0.9'
  upgrade-insecure-requests: '1'
  user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/68.0.3440.75 Chrome/68.0.3440.75 Safari/537.36'

#mysql数据库信息
db:
  host: '122.5.32.82'
  username: 'user_sourcesmt'
  passwd: 'xxxx'
  port: 8306
  dbname: 'public_source_smt'

#redis连接信息
redis:
  host: 'localhost'
  port: 6379
  password: 'sz180830'

root_cates:
#  - 'smt_women_clothing.txt'
#  - 'smt_men_clothing.txt'
#  - 'smt_cellphones.txt'
#  - 'smt_computer.txt'
#  - 'smt_consumer_electronics.txt'
#  - 'smt_jewelry.txt'
#  - 'smt_home_garden.txt'
#  - 'smt_luggage_bags.txt'
#  - 'smt_shoes.txt'
#  - 'smt_mother_kids.txt'
#  - 'smt_sports_entertainment.txt'
#  - 'smt_beauty_health.txt'
  - 'smt_watches.txt'
#  - 'smt_toys_hobbies.txt'
  - 'smt_weddings_events.txt'
  - 'smt_novelty_special.txt'
  - 'smt_automobiles.txt'
  - 'smt_furniture.txt'
  - 'smt_electronic_components.txt'
  - 'smt_office_school.txt'
  - 'smt_home_improvement.txt'
  - 'smt_security.txt'
  - 'smt_tools.txt'
  - 'smt_hair_extensions.txt'
